
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Test PowerShell
        shell: powershell
        run: |
          Write-Host "Windows Runner is working"
          Write-Host "PowerShell version:"
          $PSVersionTable.PSVersion

      - name: Test Network
        shell: powershell
        run: |
          Test-NetConnection github.com -Port 443
